// AI tools rendered as "logo stars" inside the galaxy.
// mono: badge monogram, color: badge/glow tint.
export const AI_TOOLS = [
  { name: 'ChatGPT', mono: 'G', color: '#10a37f' },
  { name: 'Claude', mono: 'C', color: '#d97757' },
  { name: 'Gemini', mono: 'G', color: '#4e86f7' },
  { name: 'Copilot', mono: 'Co', color: '#8957e5' },
  { name: 'Cursor', mono: 'Cu', color: '#7c8aff' },
  { name: 'Midjourney', mono: 'M', color: '#8aa2ff' },
  { name: 'Perplexity', mono: 'P', color: '#20b8cd' },
  { name: 'Notion AI', mono: 'N', color: '#9aa4b2' },
  { name: 'Figma AI', mono: 'F', color: '#a259ff' },
  { name: 'Runway', mono: 'R', color: '#46e3b7' },
  { name: 'ElevenLabs', mono: 'XI', color: '#6366f1' },
  { name: 'Hugging Face', mono: 'HF', color: '#ffcc4d' },
  { name: 'Stable Diffusion', mono: 'SD', color: '#a855f7' },
  { name: 'LangChain', mono: 'LC', color: '#2dd4bf' },
  { name: 'Zapier', mono: 'Z', color: '#ff4f00' },
  { name: 'n8n', mono: 'n8', color: '#ea4b71' },
  { name: 'Jasper', mono: 'J', color: '#8b5cf6' },
  { name: 'Grammarly', mono: 'Gr', color: '#15c39a' },
  { name: 'Synthesia', mono: 'Sy', color: '#38bdf8' },
  { name: 'Suno', mono: 'Su', color: '#f59e0b' },
  { name: 'Luma', mono: 'L', color: '#60c5f8' },
  { name: 'DeepL', mono: 'DL', color: '#4aa3e8' },
  { name: 'Replit', mono: 'Re', color: '#f26207' },
  { name: 'v0', mono: 'v0', color: '#cbd5e1' },
  { name: 'Lovable', mono: 'Lo', color: '#ff5b77' },
  { name: 'Windsurf', mono: 'W', color: 'var(--cyan)' },
  { name: 'Canva AI', mono: 'Ca', color: '#00c4cc' },
  { name: 'Leonardo', mono: 'Le', color: '#a78bfa' },
  { name: 'Pika', mono: 'Pk', color: '#fbbf24' },
  { name: 'Descript', mono: 'D', color: '#7c3aed' },
  { name: 'Otter', mono: 'O', color: '#3b82f6' },
  { name: 'Whisper', mono: 'Wh', color: '#10b981' },
  { name: 'Llama', mono: 'Ll', color: '#60a5fa' },
  { name: 'Mistral', mono: 'Mi', color: '#ff7000' },
  { name: 'Groq', mono: 'Gq', color: '#f97316' },
  { name: 'NotebookLM', mono: 'NL', color: '#fb7185' },
]
