// Map a stored plan id (shishya|guru|pandava) to its current display name.
// Session/authStore still stores the legacy ids; the UI shows Student/Pro/Team.
export const planLabel = (id) => PLANS.find((p) => p.id === id)?.name || id

export const PLANS = [
  {
    id: 'shishya',
    name: 'Student',
    icon: 'student',
    tier: 'Solo',
    price: 3,
    badge: null,
    glow: 'rgba(251, 113, 133, 0.28)',
    accent: '#fb7185',
    audience: 'Students, hobbyists, solo learners exploring AI',
    features: [
      'Personalized AI tool discovery (up to 5 categories)',
      'Basic learning paths (beginner to intermediate)',
      'Community access (Discord & forum)',
      'Weekly discovery digest email',
      'Save up to 10 favorite tools',
      'Basic chat support',
      '1 user profile',
    ],
  },
  {
    id: 'guru',
    name: 'Pro',
    icon: 'pro',
    tier: 'Pro',
    price: 8,
    badge: 'Most Popular',
    glow: 'rgba(124, 58, 237, 0.5)',
    accent: '#7c3aed',
    featured: true,
    audience: 'Freelancers, professionals, serious learners',
    plus: 'Everything in Student, plus:',
    features: [
      'Unlimited tool discovery (all categories)',
      'Advanced learning paths (beginner → senior)',
      'Custom tool stack builder with save & share',
      'AI-powered chat assistant (Claude-powered Q&A)',
      'Weekly trending tools + personalized alerts',
      'Unlimited favorite tools',
      'Progress tracking + skill badges',
      'Priority email support',
      'Export learning roadmaps as PDF',
    ],
  },
  {
    id: 'pandava',
    name: 'Team',
    icon: 'team',
    tier: 'Team',
    price: 50,
    badge: 'Up to 5 seats · $10/seat',
    glow: 'rgba(6, 182, 212, 0.4)',
    accent: '#06b6d4',
    audience: 'Startups, agencies, research teams, enterprise pods',
    plus: 'Everything in Pro, plus:',
    features: [
      'Up to 5 team members (5 seats included)',
      'Team stack standardization',
      'Role-based team onboarding',
      'Team analytics dashboard',
      'Collaborative tool-evaluation workspace',
      'Admin controls + member management',
      'Shared progress + team leaderboards',
      'Dedicated support channel (48hr response)',
      'Quarterly AI stack audit reports',
      'API access for integrations',
    ],
  },
]

// Rows for the "Compare All" table: [label, shishya, guru, pandava]
export const COMPARISON = [
  ['Tool discovery', '5 categories', 'Unlimited', 'Unlimited'],
  ['Learning paths', 'Basic', 'Advanced', 'Advanced'],
  ['Saved favorites', '10', 'Unlimited', 'Unlimited'],
  ['AI chat assistant', false, true, true],
  ['Stack builder + share', false, true, true],
  ['Progress tracking + badges', false, true, true],
  ['PDF roadmap export', false, true, true],
  ['Seats', '1', '1', 'Up to 5'],
  ['Team analytics dashboard', false, false, true],
  ['Admin controls', false, false, true],
  ['Quarterly stack audits', false, false, true],
  ['API access', false, false, true],
  ['Support', 'Basic chat', 'Priority email', 'Dedicated (48hr)'],
]
